### PR TITLE
Creation of python package

### PR DESCRIPTION
**Pull request by ehsteve**
Updated the code so that it is now a package using astropy helpers.

### CODE REVIEW

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
@ehsteve this now passes `python setup.py test` and `python setup.py build_docs`.

I did have to refactor your `GenericMap` subclass into a function, because it was deeply offensive to me. 😉

**Comment by Cadair** [comment]
I have also turned on Travis so merging this should trigger a travis build.

Once we have merged this we should also turn on RTD.

**Comment by ehsteve** [comment]
@Cadair I already have RTD set up [upstream](http://solar-eclipse.readthedocs.io/en/latest/) [ehsteve branch](http://ehsteve-solar-eclipse.readthedocs.io). Remind me what your user name is on RTD and I'll give you admin access.

**Comment by Cadair** [comment]
It's cadair. You good with this as-is?

**Pull request merged**
